[project]
name = "learning-python-control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "control>=0.10.2",
    "ipykernel>=7.0.1",
    "slycot>=0.6.0",
]
